@startuml Diagram
    class Invoker {

    }

    class command <<interface>>{
        +execute();
    }

    class concreteCommand{
        +execute();
    }

    class Receiver{
        +Action();
    }

    class Client{

    }

    Invoker o-- command 
    command <|.. concreteCommand
    Receiver <|-- concreteCommand
    Receiver <|-- Client
    concreteCommand <|.. Client

@enduml